---
- name: File and Directory Management
  hosts: all
  become: true
  tasks:
  - name: Create Application Directory
    file:
      path: /opt/myapp
      state: directory
      mode: '0755'
      owner: root
      group: root

  - name: Create Subdirectories
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
      owner: root
      group: root
    loop:
      - /opt/myapp/config
      - /opt/myapp/logs
      - /opt/myapp/data

  - name: Copy Config file
    copy: 
      content: |
        # Application Config
        app_name=MyApplication
        debug=false
        log_level=info
      dest: /opt/myapp/config/app.conf
      mode: '0644'
      owner: root
      group: root

  - name: Set permissions on data directory
    file:
      path: /opt/myapp/data
      mode: '0750'
      owner: root
      group: users
      recurse: yes

  - name: Create log file with specific permissions
    file: 
      path: /opt/myapp/logs/app.log
      state: touch
      mode: '0640'
      owner: root
      group: adm
